import { User } from './user.interface';

export interface Classroom {
  _id?: string; // Auto-generated by MongoDB
  tenant: string; // Tenant ID reference
  name: string; // e.g., Grade 8, LKG, UKG
  section: string; // e.g., A, B, C
  academicYear: string; // e.g., 2024-2025
  classTeacher?: User | string; // Linked User object or ID
  students?: string[] | User[]; // Array of student IDs or User objects
  createdAt?: string; // Auto from Mongoose timestamps
  updatedAt?: string; // Auto from Mongoose timestamps
  __v?: number; // Mongoose version key
}
